config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
 
  get '/products', to: 'products#new' 
  resources :products, except: [:index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
  validates :url, presence: true
  mount_uploader :url, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  validates_associated :images
  validates :images, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :price, numericality: { only_integer: true,
    greater_than: 299, less_than: 10000000 }
  validate :has_images?
  default_scope -> { order(created_at: :desc) }
  accepts_nested_attributes_for :images, allow_destroy: true

  def has_images?
    errors.add(:"images.file", "がありません") if images[0].url.blank?
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.includes(:images)
  end

  def new
    @product = Product.new
    @product.images.build
  end

  def create
    @product = Product.new(product_params)
    @product.images.build if @product.images.blank? 
    if @product.save
      flash[:success] = "出品しました。"
      redirect_to root_url
    else
      render :new   
    end
  
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, images_attributes: [:url, :url_cache, :id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = "")
    base_title = "Product App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper

  def convert_to_yen(price)
    "¥#{price.to_s(:delimited)}"
  end

  def display_error_messages(object, attribute)
    if object.errors[attribute].any?
      content_tag(:div, class: "error-messages", id: attribute) do
        object.errors.full_messages_for(attribute).map do |message|
        concat(content_tag(:p, message, class: "error-message"))
        end
      end
    end  
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar">
  <nav class="footer-nav">
    <div class="nav-menu">
      <h2>Product Appについて</h2>
      <ul class="menu-lists">
        <li class="menu-list">
          <a class="under-line" href="https://github.com/higasimaru/" target="_blank">GitHub</a>
        </li>
        <li class="menu-list">
          <a class="under-line" href="https://higasimaru.github.io/" target="_blank">関連サイト</a>
        </li>
      </ul>
    </div>
    <div class="nav-menu">
      <h2>ヘルプ＆ガイド</h2>
      <ul class="menu-lists">
        <li class="menu-list">
          <a class="under-line" href="https://github.com/higasimaru/product_app"
            target="_blank">Product Appガイド
          </a>
        </li>
        <li class="menu-list">
          <a class="under-line" href="https://github.com/higasimaru/product_app"
            target="_blank">出品について
          </a>
        </li>
      </ul>
    </div>
    <div class="nav-menu">
      <h2>プライバシーと利用規約</h2>
      <ul class="menu-lists">
        <li class="menu-list">
          <a class="under-line" href="#">プライバシーポリシー</a>
        </li>
        <li class="menu-list">
          <a class="under-line" href="https://github.com/higasimaru/product_app"
            target="_blank">Product App利用規約
          </a>
        </li>
      </ul>
    </div>
    <div class="nav-menu sns-icon">
      <h2>SNS</h2>
      <ul class="menu-lists">
        <li class="menu-list">
          <a href="https://twitter.com/home" target="_blank">
            <i class="fab fa-twitter-square"></i>
          </a>
        </li>
        <li class="menu-list">
          <a href="https://line.me/ja/"><i class="fab fa-line"></i></a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="footer-logo">
    <%= link_to "Product App", root_path, id: "logo" %>
    <span>©️ Product App, Inc.</span>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]> 
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script> 
  <![endif]-->
</head>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="header-container">
    <%= link_to "Product App", root_path, id: "logo" %>
    <div class="header-form">
      <input type="text" class="search-form" placeholder="何をお探しですか？">
      <button class="btn">
        <i class="fas fa-search"></i>
      </button>
    </div>
    <nav> 
      <ul class="nav navbar-left">
        <li>
          <i class="fas fa-bars"></i>
          <span>カテゴリーから探す</span>
        </li>
        <li>
          <i class="fas fa-tag"></i>
          <span>ブランドから探す</span></li>
      </ul>
      <ul class="nav navbar-right">
        <li>
          <i class="far fa-heart"></i>
          <span>いいね!一覧</span>
        </li>
        <li>
          <i class="far fa-bell"></i>
          <span>お知らせ</span>
        </li>
        <li>
          <i class="fas fa-check"></i>
          <span>やることリスト</span>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>
  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="flash-box">
          <i class="fas fa-check-circle"></i>
          <%= content_tag :span, value, class: "alert alert-#{key}"%>
          <i class="fa fa-times"></i>
        </div>
      <% end %>
    </div>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |f| %>
  <div class="preview-modal-container">
    <%= render "products/modal"%>  
  </div>  
  <div class="product-form">
    <div class="form-label">
      <label for="product_images_attributes_0_url">出品画像</label>
      <span>必須</span>
    </div>
    <p>最大10枚までアップロードできます</p>
    <div class="file-box">
      <div class="preview-files"> 
        <%= render partial: "shared/upper_preview" %>
      </div>
      <label id="file-label">
        <p>
          <i class="fa fa-camera"></i><br>
          <span id="file-message">
            ドラッグアンドドロップ<br>
            またはクリックでファイルをアップロード
          </span>
        </p>
        <%= f.fields_for :images do |image| %>
          <div class="file-form" data-index="<%=image.index%>">
            <%= image.file_field :url, id: "file" %>
            <%= image.hidden_field :url_cache %>
          </div>
        <% end %>
      </label>
    </div>
    <div class="new-file-box">
      <div class="new-preview-files">
        <%= render "shared/under_preview" %>   
      </div>
    </div>
    <%= display_error_messages(f.object, :"images.file") %>
  </div>
  <div class="product-form">
    <div class="form-label">
      <%= f.label :name, "商品名" %>
      <span>必須</span>
    </div>
    <div class="name-form">   
      <%= f.text_field :name, placeholder: "40文字まで", maxlength: "40" %>
    </div>
    <%= display_error_messages(f.object, :name) %>
  </div>
  <div class="product-form product-form_noline">
    <p class="price-caution">価格　(¥300〜9,999,999)</p>
    <div class="form-label price-label">
      <%= f.label :price, "販売価格" %>
      <span>必須</span>
      <i class="fas fa-yen-sign"></i>
      <%= f.number_field :price, class: "price-form", id: "price", placeholder: "0" %>    
    </div>
    <%= display_error_messages(f.object, :price) %>
    <div class="price-fee">
      <p>販売手数料　(10%)</p>
      <span>ー</span>
    </div>
    <div class="price-profit">
      <p>販売利益</p>
      <span>ー</span>
    </div>
  </div>
  <div class="product-form product-form_bottom">
    <%= f.submit "出品する", class: "btn" %>
    <input type="button" class="btn btn-draft" value="下書きに保存">
    <%= link_to "もどる", root_path, class: "return-btn" %>
  </div>
  <div class="product-form">
    <p class="product-caution">
      禁止されている<a href="#">行為</a>
      および<a href="#">出品物</a>
      を必ずご確認下さい。<a href="#">偽ブランド品</a>
      や<a href="#">盗品物</a>
      などのなどの販売は犯罪であり、法律に法律により処罰される可能性があります。
      また、出品をもちまして<a href="#">加盟店規約</a>
      に同意したことになります。
    </p>   
  </div>
<% end %>
  

app/views/products/_modal.html.erb
<% if @product.images[0].url.present? %>
  <% @product.images.each_with_index do |image, i| %>
    <div class="preview-modal-wrapper" data-modal="<%= i %>">
      <div class="preview-modal">
        <div class="preview-nav">
          <p>写真を切り取る</p>
          <div class="remove-btn">
            <i class="fas fa-trash-alt"></i>
            <span>削除する</span>
          </div>
        </div>
        <div class="modal-image-box">
          <div class="modal-image-frame">
            <%= image_tag image.url.url, data: { modal_image: i }, class: "modal-image" %>
          </div>
          <div class="modal-slide">
            <i class="fas fa-camera small-camera"></i>
            <input type="range">
            <i class="fas fa-camera large-camera"></i>
          </div>
        </div>
        <div class="submit-btns">
          <input type="button" class="modal-btn" value="キャンセル">
          <input type="button" class="modal-btn decision-btn" value="完了">
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<ul class="product">
  <li class="main-image">
    <% product.images.each do |image| %>
      <%= image_tag image.url.url %>
    <% end %>
    <span class="product-price">
    <%= convert_to_yen(product.price) %>
    </span>
  </li>
  <li class="sub-images clearfix">
    <% product.images.each do |image| %>
      <%= image_tag image.url.url, class: "sub-image hide-image" %>
    <% end %>
  </li>
  <li class="product-name">
    <span><%= product.name %></span>
  </li> 
</ul>

app/views/products/_products.html.erb
<li>
  <%= product.images.each do |image| %>
    <%= image_tag image.url %>
  <% end%>
  <%= product.name %>
  <%= product.price %>
</li>

app/views/products/index.html.erb
<%= render "layouts/header" %>
<div class="row">
  <div class="category-navi">
    <h1>人気のカテゴリー</h1>
    <ul>
      <li><a href="#">レディース</a></li>
      <li><a href="#">メンズ</a></li>
      <li><a href="#home-appliances">家電・スマホ・カメラ</a></li>
      <li><a href="#">おもちゃ・ホビー・グッズ</a></li>
    </ul>
  </div>
  <div class="wrapper">
    <h1><a id="home-appliances">家電・スマホ・カメラ 新着アイテム</a></h1>
    <div class="products">
      <%= render partial: "product", collection: @products %>
    </div>
    <%= link_to new_product_path, class: "exhibition", data: { turbolinks: false} do %>
      <div class="exhibition-btn">
        <p>出品</p>
        <i class="fa fa-camera"></i>
      </div>
    <% end %> 
  </div>
</div>

app/views/products/new.html.erb
<% provide(:title, "出品") %>
<div class="row">
  <h1>
    <%= link_to "Product App", root_path, class: "product-logo" %>
  </h1> 
  <div class="product-wrapper">    
    <%= render "products/form" %>
  </div>
</div>

app/views/shared/_under_preview.html.erb
<% if @product.images[5].present? %>
  <% next_images = @product.images[5..-1] %>
  <% next_images.each_with_index do |image, i| %>
    <div class="preview-file" data-preview="<%= i + 5 %>">
      <%= image_tag image.url.url, class: "preview-image", data: { preview_image: i + 5 } %>
      <div class="edit-btn">編集</div>
    </div>
  <% end %>
<% end %>

app/views/shared/_upper_preview.html.erb
<% if @product.images[0].url.present? %>
  <% images = @product.images[0..4] %> 
  <% images.each_with_index do |image, i| %>
    <div class="preview-file" data-preview="<%= i %>">
      <%= image_tag image.url.url, class: "preview-image", data: { preview_image: i } %>
      <div class="edit-btn">編集</div>
    </div>
  <% end %>
<% end %>